language: node_js
sudo: false
node_js:
  - 5.6
install:
- npm install purescript bower pulp purescript-psa -g
- bower install
script:
  - pulp build --censor-lib
  - bower link
  - cd examples/halogen-storage/ && bower link purescript-webstorage-free && bower install && pulp build --censor-lib && cd ..
  - cd examples/halogen-storaget-aff/ && bower link purescript-webstorage-free && bower install && pulp build --censor-lib && cd ..

