language: node_js
sudo: false
node_js:
  - 5.6
install:
- npm install purescript bower pulp -g
- bower install
script:
  - pulp build
  - bower link
  - cd examples/halogen-storage/ && bower link purescript-websocket-simple && bower install && pulp build
